# Generated by Django 5.0.4 on 2024-04-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('subjectCode', models.CharField(max_length=100)),
                ('timeDuration', models.DurationField()),
                ('totalMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_id', models.IntegerField()),
                ('question', models.TextField()),
                ('ques_num', models.IntegerField()),
                ('code', models.TextField(blank=True, default='')),
                ('desired_output', models.TextField()),
                ('max_score', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.test')),
            ],
        ),
    ]
