# Generated by Django 5.0.4 on 2024-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='examcode',
            field=models.CharField(default='123AB', max_length=100),
        ),
    ]
