# Generated by Django 5.0.2 on 2024-04-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subject_Code', models.CharField(max_length=100)),
                ('total_Marks', models.IntegerField(default=100)),
                ('exam_code', models.CharField(default='123AB', max_length=100)),
            ],
        ),
    ]
