# Generated by Django 5.0.2 on 2024-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_test_examcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='examcode',
            new_name='exam_code',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='subject_Code',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='timeDuration',
            new_name='time_Duration',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='totalMarks',
            new_name='total_Marks',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subjectCode',
        ),
        migrations.AddField(
            model_name='test',
            name='date_and_time',
            field=models.DateTimeField(default=None),
        ),
    ]
