# Generated by Django 5.0.4 on 2024-04-06 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_examcode_test_exam_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 16, 44, 39, 324306, tzinfo=datetime.timezone.utc)),
        ),
    ]
