# Generated by Django 5.0.4 on 2024-04-06 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_test_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 16, 46, 3, 992488, tzinfo=datetime.timezone.utc)),
        ),
    ]
