# Generated by Django 5.0.4 on 2024-04-06 15:47

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_test_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_and_time',
            field=models.DateTimeField(default=teacher.models.one_hour_from_now),
        ),
    ]
