# Generated by Django 5.0.4 on 2024-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_test_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_Duration',
            field=models.DurationField(default=3),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_Marks',
            field=models.IntegerField(default=100),
        ),
    ]
