# Generated by Django 5.0.4 on 2024-04-06 15:49

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_test_time_duration_alter_test_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_and_time',
            field=models.DateTimeField(default=teacher.models.one_hour_from_now, null=True),
        ),
    ]
