# Generated by Django 5.0.4 on 2024-04-06 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datecreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test',
            name='exam_code',
            field=models.CharField(default='123AB', max_length=200),
        ),
    ]
