# Generated by Django 5.0.4 on 2024-04-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0002_test_datecreated_test_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.IntegerField(default=1),
        ),
    ]
