# Generated by Django 5.0.2 on 2024-04-06 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0003_question_max_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_marks', models.IntegerField()),
                ('exam_code', models.CharField(default='123AB', max_length=200)),
            ],
        ),
    ]
