# Generated by Django 5.0.2 on 2024-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0004_publishedtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='published_bool',
            field=models.BooleanField(default=False),
        ),
    ]
