# Generated by Django 5.0.2 on 2024-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0005_test_published_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedtest',
            name='published_bool',
            field=models.BooleanField(default=False),
        ),
    ]
