# Generated by Django 5.0.4 on 2024-04-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeTest', '0006_publishedtest_published_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(default='', null=True),
        ),
    ]
